/*******************  McAfee CONFIDENTIAL AND PROPRIETARY  **************************
*
*  Copyright (c) 2017 McAfee Inc.  All Rights Reserved.
*
*  This file and the information contained herein is the confidential and
*  proprietary information of Intel Corporation.  Your rights to this file and its
*  information are subject to the terms of the license agreement between
*  Intel Corporation and you or your company.
*
********************  McAfee CONFIDENTIAL AND PROPRIETARY  **************************/

mcafee_wa_annotationoptions={Unknown:-1,None:1,OnlySecureSearch:2,All:4};
var mcafee_wa_bkconstants={uninstallUrl:"https://home.mcafee.com/root/landingpage.aspx?lpname=get-it-now",siteAdvisorUrl:"http://www.siteadvisor.com/",siteAdvisorUrlSecure:"https://www.siteadvisor.com/",siteReportUrl:"https://www.mcafee.com/threat-intelligence/site/default.aspx?url=",blockPageUrl:"https://www.siteadvisor.com/restricted.html",phishingPageUrl:"https://www.siteadvisor.com/phishing.html",maxCacheRecords:1E3,browsertype:"browsertype",useragent:"useragent",whitelistUrl:"about:blank?command=whitelist&token=1",
domain:"domain",redirectURL:"redirectURL",originalURL:"originalURL",chromeExtensionVersion:"chromeExtVer",disabled:"disabled",notchromecompliant:"SearchExtensionDisabled",viewport:"viewport",annonlyonssearch:"*OnlyShowAnnotationsOnSecureSearch",showicons:"*Icons",pnaclenabled:"Pnaclenabled",phishingcategory:169},mcafee_wa_browseraction=function(){return{disable:function(a){null!=chrome.browserAction&&"undefined"!=typeof chrome.browserAction&&chrome.browserAction.disable(a)},setTitle:function(a){null!=
chrome.browserAction&&"undefined"!=typeof chrome.browserAction&&chrome.browserAction.setTitle({title:a})},setIcon:function(a,b){null!=chrome.browserAction&&"undefined"!=typeof chrome.browserAction&&("undefined"!=typeof b?chrome.browserAction.setIcon({path:a,tabId:b}):chrome.browserAction.setIcon({path:a}))}}}();mcafee_wa_browsertypes={Unknown:-1,Firefox:1,Chrome:2,McAfeeSecureBrowser:3,Opera:4,Edge:5,Agnostic:6};function mcafee_wa_cache(){}mcafee_wa_cache.prototype.set=function(a,b){};
mcafee_wa_cache.prototype.get=function(a){};mcafee_wa_color={SA_Green:0,SA_Yellow:1,SA_Red:2,SA_Unknown:3,SA_HackerSafe:4,SA_Cashback:5,SA_Disabled:6};
var mcafee_wa_commands={dssrequest:"dssrequest",reportstat:"reportstat",executecommand:"executecommand",ondoccomplete:"ondoccomplete",onnavigateiframe:"onnavigateiframe",onredirectiframe:"onredirectiframe",onnavigate:"onnavigate",onoptionreceived:"onoptionreceived",setoption:"setoption",getsupportedfeatures:"getsupportedfeatures",isframeblocked:"isframeblocked",whitelistediframe:"whitelistediframe",ispageblocked:"ispageblocked",logmsg:"logmsg",getxyviewport:"getxyviewport"},mcafee_wa_disabledflags=
{disabledChrome:1,disabledSafeBrowser:2,disabledFirefox:4,disabledEdge:8,disabledOpera:16};mcafee_wa_extensionmsgs={setoptionstring:1,sendtelemetry:2,ping:3,syncoptionsfrommain:4};mcafee_wa_extensiontypes={Unknown:-1,Main:0,Search:1};
var mcafee_wa_jscommands={addbitmap:"addBitmap",addcontexttomap:"addContextToMap",addctxref:"addCtxRef",addurlhash:"addUrlHash",changebitmap:"changeBitmap",geturlhash:"getUrlHash",idfromcontext:"idFromContext",navigate:"navigate",removectxref:"removeCtxRef",tryaddpasswordhandler:"tryAddPasswordHandler",urlfromcontext:"urlFromContext",getxyviewport:"getxyviewport",refreshsettings:"refreshSettings"},mcafee_wa_loggertype={defaultLogger:0,nativeLogger:1};mcafee_wa_logtypes={None:0,Info:1,Err:2,All:3};
var mcafee_wa_nativecommands={activate:"activate",ondownloadfinished:"onDownloadFinished",reportstat:"reportStat",ondssrequest:"onDssRequest",onbeforenavigate:"onBeforeNavigate",onnavigate:"onNavigate",ondoccomplete:"onDocComplete",executecommand:"executeCommand",onMenuItemClick:"onMenuItemClick",setsystemoptionstring:"setSystemOptionString",getsystemoptionstring:"getSystemOptionString",getsystemoptionbool:"getSystemOptionBool",onCSync:"onCSync",logmsg:"logMsg"};
function mcafee_wa_onbeforesendheaderlistener(){}mcafee_wa_onbeforesendheaderlistener.prototype.init=function(){};function mcafee_wa_promise(){this.pThis=this.commandParams=this.command=this.promise=this.reject=this.resolve=null}mcafee_wa_promise.prototype.createPromise=function(a,b,d,c,e,f){this.resolve=b;this.reject=d;this.command=c;this.commandParams=e;this.pThis=f;return this.promise=new Promise(a)};mcafee_wa_scorevals={ScoreMinimal:15,ScoreUnknown:30,ScoreMedium:50};
var mcafee_wa_searchoption={securesearch:1,anysearch:2,nosearch:0},mcafee_wa_supportedfeatures={none:0,annotations:1,blockpages:2,iframeblocking:4},mcafee_wa_telemetrycounters={incrstatsrchitunk:"INCREMENTSTAT_SearchHit_Unknown_",incrstat:"INCREMENTSTAT_",browsererr:"BrowserError"},mcafee_wa_uriparser=function(){return{getParam:function(a,b){var d=a.split("?");if(2!=d.length)return null;for(var d=d[1].split("&"),c=0;c<d.length;++c){var e=d[c].split("=");if(2==e.length&&e[0]==b)return e[1]}return null},
getURI:function(a){var b=a.split("?");return 2>b.length&&(hashParts=a.split("#"),2<=hashParts.length)?hashParts[0]:b[0]}}}(),mcafee_wa_browsertypefinder=function(){return{getBrowserType:function(a){return a==mcafee_wa_browsertypes.Chrome&&/Secure\//.test(navigator.userAgent)?mcafee_wa_browsertypes.McAfeeSecureBrowser:a},browserTypeToString:function(a){switch(a){case 1:return"FF";case 2:return"CH";case 3:return"MSB";case 4:return"OP";case 5:return"ED";case 6:return"AG"}return"UN"}}}();
function mcafee_wa_logger(){this._logTypes=mcafee_wa_logtypes.None}mcafee_wa_logger.prototype.SetLogTypes=function(a){this._logTypes=a};mcafee_wa_logger.prototype.log=function(a){mcafee_wa_logtypes.Info&this._logTypes&&console.log((new Date).toLocaleString()+" "+a)};mcafee_wa_logger.prototype.error=function(a){mcafee_wa_logtypes.Err&this._logTypes&&console.error((new Date).toLocaleString()+" "+a)};
var mcafee_wa_supportedextensions=function(){return{isExtensionSupported:function(a){return"lalnlkdjolkfkfgaicmnjegcfeelnhkj"==a||"lmjfclhkpjjgloekikcgameicbjbgpjg"==a||"fheoggkfdfchfphceeifdbepaooicaho"==a?!0:!1},getBuddyExtensions:function(){var a=[];mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?(a.push("lalnlkdjolkfkfgaicmnjegcfeelnhkj"),a.push("lmjfclhkpjjgloekikcgameicbjbgpjg")):a.push("fheoggkfdfchfphceeifdbepaooicaho");return a}}}(),mcafee_wa_globals=function(){var a=new mcafee_wa_logger,
b=new Map;return{uid:"{0DE9E47C-871A-4F90-8440-B190C216800A}",resourceRequestor:null,dssRequestor:null,resourceRootURI:null,annotationProperties:null,balloonProperties:null,reputationReqCount:10,annotationEvents:null,activeBalloonElement:null,debugMode:!1,logger:a,activeURI:null,mapSelectors:b,cacheStats:{},imageCounter:0,eventHandler:null,binjectBalloon:!1,debugTitle:"",onlyShowMcAfeeSecure:!1}}();function mcafee_wa_resourcerequestor(){this._messages=null}
mcafee_wa_resourcerequestor.prototype.getURI=function(a){var b=null;return b=null!=mcafee_wa_globals.resourceRootURI?mcafee_wa_globals.resourceRootURI+a:chrome.extension.getURL(a)};
mcafee_wa_resourcerequestor.prototype.getImage=function(a,b){try{var d=new XMLHttpRequest,c=this.getURI("images/"+a);d.open("GET",c,!0);d.responseType="blob";d.onload=function(a){if(4==d.readyState&&200==d.status){var c=new FileReader;c.onloadend=function(){b(c.result)};c.readAsDataURL(d.response)}};d.onerror=function(b){mcafee_wa_globals.logger.error("Failed in requesting html: "+a+b)};d.send(null)}catch(e){mcafee_wa_globals.logger.error(e)}};
mcafee_wa_resourcerequestor.prototype.getContent=function(a,b,d){try{var c=new XMLHttpRequest,e=this.getURI(b+a);c.open("GET",e,!0);c.onload=function(a){4==c.readyState&&200==c.status&&d(c.responseText)};c.onerror=function(b){mcafee_wa_globals.logger.error("Failed in requesting :"+a+b)};c.send(null)}catch(f){mcafee_wa_globals.logger.error(f)}};mcafee_wa_resourcerequestor.prototype.getJSON=function(a,b){this.getContent(a,"json/",b)};
mcafee_wa_resourcerequestor.prototype.getHtml=function(a,b){this.getContent(a,"html/",b)};mcafee_wa_resourcerequestor.prototype.getResStr=function(a,b){if(null!=mcafee_wa_globals.resourceRootURI){var d=this;null==this._messages?this.getContent("messages.json","_locales/"+window.navigator.language,function(c){null!=c&&(d._messages=JSON.parse(c),null!=d._messages&&b(d._messages[a].message))}):b(d._messages[a].message)}else{var c=chrome.i18n.getMessage(a);"??"==c&&(c="");b(c)}};
var mcafee_wa_bkglobals=function(){var a=new mcafee_wa_logger,b=new mcafee_wa_cache,d=new Map,c=new Map,e=new Map;return{isNewUserWelcomeDisabled:!1,messageDispatcher:null,activetabId:-1,logger:a,cache:b,options:d,blockPageMap:c,walite:null,pnaclFnMap:e,annotationOption:mcafee_wa_annotationoptions.Unknown,otherExtensionEnabled:!1,pnaclIdIter:0,searchURL:null,isChromeCompliant:!1,pnaclEnabled:0,pnaclInSearchEnabled:-1,isPProtectFeatureDisabled:!0,hasUserDisabledPProtect:!0,lastUrl:null}}(),mcafee_wa_msgdispatchhelper=
function(){return{toQualifiedImagePath:function(a){a=a.startsWith("small_")?"images/"+a:"images/small_"+a;return(new mcafee_wa_resourcerequestor).getURI(a)}}}(),mcafee_wa_settings={loggertype:mcafee_wa_loggertype.defaultLogger,logtype:mcafee_wa_logtypes.None,debugmode:!1,browsertype:mcafee_wa_browsertypes.Chrome,extnversion:"5.1.0.629",extensiontype:mcafee_wa_extensiontypes.Main},mcafee_wa_bkcommon=function(){return{toColor:function(a){var b=mcafee_wa_color.SA_Unknown;return b=a<mcafee_wa_scorevals.ScoreMinimal?
mcafee_wa_color.SA_Green:a<mcafee_wa_scorevals.ScoreUnknown?mcafee_wa_color.SA_Unknown:a<mcafee_wa_scorevals.ScoreMedium?mcafee_wa_color.SA_Yellow:mcafee_wa_color.SA_Red},isDisabled:function(a,b){for(var d=[{browser:mcafee_wa_browsertypes.Chrome,flag:mcafee_wa_disabledflags.disabledChrome},{browser:mcafee_wa_browsertypes.McAfeeSecureBrowser,flag:mcafee_wa_disabledflags.disabledSafeBrowser},{browser:mcafee_wa_browsertypes.Firefox,flag:mcafee_wa_disabledflags.disabledFirefox},{browser:mcafee_wa_browsertypes.Edge,
flag:mcafee_wa_disabledflags.disabledEdge},{browser:mcafee_wa_browsertypes.Opera,flag:mcafee_wa_disabledflags.disabledOpera}],c=0;c<d.length;++c)if(d[c].browser==b)return 0!=(d[c].flag&a)?!0:!1;return!1},isSiteAdvisorURL:function(a){return a.startsWith(mcafee_wa_bkconstants.siteAdvisorUrl)||a.startsWith(mcafee_wa_bkconstants.siteAdvisorUrlSecure)?!0:!1},isProperWebURL:function(a){return a.startsWith("http://")||a.startsWith("https://")||a.startsWith("ftp://")?!0:!1},toStringExtensionType:function(a){return a==
mcafee_wa_extensiontypes.Main?" (Main)":" (Search)"}}}();function mcafee_wa_bknativelogger(){this._logTypes=mcafee_wa_logtypes.None}mcafee_wa_bknativelogger.prototype.SetLogTypes=function(a){this._logTypes=a};mcafee_wa_bknativelogger.prototype.log=function(a){mcafee_wa_logtypes.Info&this._logTypes&&mcafee_wa_bkglobals.messageDispatcher.logMsg(16777216|mcafee_wa_bkglobals.browserType<<16|mcafee_wa_logtypes.Info,a)};
mcafee_wa_bknativelogger.prototype.error=function(a){mcafee_wa_logtypes.Err&this._logTypes&&mcafee_wa_bkglobals.messageDispatcher.logMsg(16777216|mcafee_wa_bkglobals.browserType<<16|mcafee_wa_logtypes.Err,a)};
var mcafee_wa_dispatchwrap=function(){return{onBeforeNavigate:function(a,b,d){if(!mcafee_wa_extensionstatuschecker.isBlockPageDisabled())mcafee_wa_bkglobals.messageDispatcher.onBeforeNavigate(a,b,d)},onNavigate:function(a,b,d){if(!mcafee_wa_extensionstatuschecker.isBlockPageDisabled())mcafee_wa_bkglobals.messageDispatcher.onNavigate(a,b,d)},onDocComplete:function(a){if(!mcafee_wa_extensionstatuschecker.isBlockPageDisabled())mcafee_wa_bkglobals.messageDispatcher.onDocComplete(a)}}}();
function mcafee_wa_managementlistener(){}
mcafee_wa_managementlistener.prototype.init=function(){chrome.management.onInstalled.addListener(function(a){});chrome.management.onUninstalled.addListener(function(a){mcafee_wa_supportedextensions.isExtensionSupported(a)&&(mcafee_wa_bkglobals.otherExtensionEnabled=!1)});chrome.management.onEnabled.addListener(function(a){mcafee_wa_supportedextensions.isExtensionSupported(a.id)&&(mcafee_wa_bkglobals.otherExtensionEnabled=!0)});chrome.management.onDisabled.addListener(function(a){mcafee_wa_supportedextensions.isExtensionSupported(a.id)&&(mcafee_wa_bkglobals.otherExtensionEnabled=
!1)})};function mcafee_wa_onchangeddownloadslistener(){}
mcafee_wa_onchangeddownloadslistener.prototype.init=function(){mcafee_wa_bkglobals.logger.log("adding download listener");try{mcafee_wa_settings.browsertype==mcafee_wa_browsertypes.Firefox?chrome.downloads.onCreated.addListener(function(a){var b=setInterval(function(){chrome.downloads.search({id:a.id},function(a){0==a.length&&clearInterval(b);var c=!1;a.forEach(function(a){"complete"==a.state?(mcafee_wa_bkglobals.logger.log("Firing download finished for item: "+a.filename),mcafee_wa_bkglobals.messageDispatcher.onDownloadFinished(a)):
"in_progress"==a.state&&(c=!0)});c||clearInterval(b)})},1E3)}):chrome.downloads.onChanged.addListener(function(a){try{mcafee_wa_bkglobals.logger.log("download event received"),null!=a&&null!=a.state&&"complete"==a.state.current&&(mcafee_wa_bkglobals.logger.log("download completed"),chrome.downloads.search({id:a.id},function(a){a.forEach(function(a){mcafee_wa_bkglobals.messageDispatcher.onDownloadFinished(a)})}))}catch(b){mcafee_wa_bkglobals.logger.error(b)}})}catch(a){mcafee_wa_bkglobals.logger.error(a)}};
function mcafee_wa_webrequestlistener(){}
mcafee_wa_webrequestlistener.prototype.init=function(){chrome.webRequest.onBeforeRequest.addListener(function(a){if(!mcafee_wa_bkcommon.isSiteAdvisorURL(a.url))mcafee_wa_dispatchwrap.onBeforeNavigate(a.url,a.tabId,a.frameId)},{urls:["http://*/*","https://*/*","ftp://*/*"],types:["main_frame","sub_frame"]});chrome.webRequest.onCompleted.addListener(function(a){mcafee_wa_bkcommon.isSiteAdvisorURL(a.url)||(mcafee_wa_dispatchwrap.onNavigate(a.url,a.tabId,a.frameId),mcafee_wa_dispatchwrap.onDocComplete(a.url))},
{urls:["http://*/*","https://*/*","ftp://*/*"],types:["main_frame","sub_frame"]});chrome.webRequest.onErrorOccurred.addListener(function(a){mcafee_wa_bkglobals.messageDispatcher.onNavigate(a.url,a.tabId,a.frameId)},{urls:["http://*/*","https://*/*"],types:["main_frame"]})};
var mcafee_wa_extensionstatuschecker=function(){var a=function(){return"ja"==window.navigator.language||"jp"==window.navigator.language||"ja_JP"==window.navigator.language};return{isJapanese:a,isBlockPageDisabled:function(){return mcafee_wa_settings.browsertype!=mcafee_wa_browsertypes.Chrome?!1:mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?!1:0==mcafee_wa_bkglobals.otherExtensionEnabled&&1==mcafee_wa_bkglobals.pnaclEnabled?!1:!0},isAnnotationDisabled:function(){return mcafee_wa_settings.browsertype!=
mcafee_wa_browsertypes.Chrome?!1:0==mcafee_wa_bkglobals.otherExtensionEnabled?mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?mcafee_wa_bkglobals.isChromeCompliant?mcafee_wa_bkglobals.annotationOption==mcafee_wa_annotationoptions.All||a()?!1:!0:!1:0==mcafee_wa_bkglobals.pnaclEnabled?!0:!1:mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?mcafee_wa_bkglobals.annotationOption==mcafee_wa_annotationoptions.All||a()?!1:1==mcafee_wa_bkglobals.pnaclInSearchEnabled?!0:!1:0==
mcafee_wa_bkglobals.pnaclEnabled?!0:mcafee_wa_bkglobals.annotationOption==mcafee_wa_annotationoptions.All||a()?!0:!1},initExtensionStatus:function(){chrome.management.getAll(function(a){chrome.management.getSelf(function(d){for(var c=0;c<a.length;++c){var e=a[c];if(e.id!=d.id&&mcafee_wa_supportedextensions.isExtensionSupported(e.id)){mcafee_wa_bkglobals.otherExtensionEnabled=e.enabled;break}}})})}}}();function mcafee_wa_pingsender(){}
mcafee_wa_pingsender.prototype.ping=function(a,b){chrome.runtime.sendMessage(a,{id:mcafee_wa_extensionmsgs.ping,pnaclenabled:mcafee_wa_bkglobals.pnaclEnabled},null,function(d){"undefined"!=typeof d&&"ping"==d?b.set(a,!0):b.set(a,!1);d=mcafee_wa_supportedextensions.getBuddyExtensions();for(var c=!1,e=0;e<d.length;++e)1==b.get(d[e])&&(c=!0);mcafee_wa_bkglobals.otherExtensionEnabled=c})};
mcafee_wa_pingsender.prototype.init=function(){var a=mcafee_wa_supportedextensions.getBuddyExtensions(),b=new Map,d=this;setInterval(function(){for(var c=0;c<a.length;++c)d.ping(a[c],b)},3E3)};function mcafee_wa_extensionmsglistener(){}
mcafee_wa_extensionmsglistener.prototype.init=function(){chrome.runtime.onMessageExternal.addListener(function(a,b,d){var c=!1;if(mcafee_wa_supportedextensions.isExtensionSupported(b.id))switch(a.id){case mcafee_wa_extensionmsgs.setoptionstring:mcafee_wa_bkglobals.annotationOption=a.option;break;case mcafee_wa_extensionmsgs.sendtelemetry:mcafee_wa_bkglobals.messageDispatcher.reportStat(a);break;case mcafee_wa_extensionmsgs.ping:"undefined"!=typeof a.pnaclenabled&&mcafee_wa_bkglobals.pnaclInSearchEnabled!=
a.pnaclenabled&&(mcafee_wa_bkglobals.pnaclInSearchEnabled=a.pnaclenabled,mcafee_wa_bkglobals.messageDispatcher.setSystemOptionString(mcafee_wa_bkconstants.pnaclenabled,mcafee_wa_bkglobals.pnaclInSearchEnabled.toString()));d("ping");c=!0;break;case mcafee_wa_extensionmsgs.syncoptionsfrommain:mcafee_wa_bkglobals.messageDispatcher.syncOptionsToSearchExt()}return c})};
var mcafee_wa_suitetype={issuite:1,isfreemium:2,isorphaned:4},mcafee_wa_blockpageuri=function(){var a=null;return{getBlockPageURI:function(b,d,c,e){var f=chrome.i18n.getUILanguage(),g=f.includes("_")?f.split("_"):f.split("-"),h=2==g.length?g[1]:f;null==a&&(a=new Map,a.set("US",{langval:"",frcode:"mcafee"}),a.set("AR",{langval:"ar.",frcode:"mcafee"}),a.set("AU",{langval:"au.",frcode:"mcafee"}),a.set("BR",{langval:"br.",frcode:"mcafee"}),a.set("CA",{langval:"ca.",frcode:"mcafee"}),a.set("FR",{langval:"fr.",
frcode:"mcafee"}),a.set("DE",{langval:"de.",frcode:"mcafee"}),a.set("HK",{langval:"hk.",frcode:"mcafee"}),a.set("IN",{langval:"in.",frcode:"mcafee"}),a.set("IT",{langval:"it.",frcode:"mcafee"}),a.set("KR",{langval:"kr.",frcode:"mcafee"}),a.set("MX",{langval:"mx.",frcode:"mcafee"}),a.set("ES",{langval:"es.",frcode:"mcafee"}),a.set("TW",{langval:"tw.",frcode:"mcafee"}),a.set("GB",{langval:"uk.",frcode:"mcafee"}),a.set("CF",{langval:"cf.",frcode:"mcafee"}),a.set("CL",{langval:"cl.",frcode:"mcafee"}),
a.set("CO",{langval:"co.",frcode:"mcafee"}),a.set("ID",{langval:"id.",frcode:"mcafee"}),a.set("NZ",{langval:"nz.",frcode:"mcafee"}),a.set("PE",{langval:"pe.",frcode:"mcafee"}),a.set("PH",{langval:"ph.",frcode:"mcafee"}),a.set("SG",{langval:"sg.",frcode:"mcafee"}),a.set("TH",{langval:"th.",frcode:"mcafee"}),a.set("E1",{langval:"espanol.",frcode:"mcafee"}),a.set("VE",{langval:"ve.",frcode:"mcafee"}),a.set("VN",{langval:"vn.",frcode:"mcafee"}),a.set("MY",{langval:"malaysia.",frcode:"mcafee"}),a.set("PT",
{langval:"",frcode:"mcafee_uninternational"}),a.set("BE",{langval:"",frcode:"mcafee_uninternational"}),a.set("NL",{langval:"nl.",frcode:"mcafee"}),a.set("DK",{langval:"dk.",frcode:"mcafee"}),a.set("FI",{langval:"fi.",frcode:"mcafee"}),a.set("NO",{langval:"no.",frcode:"mcafee"}),a.set("SE",{langval:"se.",frcode:"mcafee"}),a.set("CZ",{langval:"",frcode:"mcafee_uninternational"}),a.set("CH",{langval:"ch.",frcode:"mcafee"}),a.set("AT",{langval:"at.",frcode:"mcafee"}),a.set("GR",{langval:"",frcode:"mcafee_uninternational"}),
a.set("RU",{langval:"ru.",frcode:"mcafee_uninternational"}),a.set("PL",{langval:"pl.",frcode:"mcafee_uninternational"}),a.set("TR",{langval:"tr.",frcode:"mcafee_uninternational"}),a.set("HU",{langval:"",frcode:"mcafee_uninternational"}));var k=a.get(h);null==k&&(k=a.get("US"));g=new Date;b=encodeURIComponent(b);h=mcafee_wa_settings.browsertype.toString()+mcafee_wa_suitetype.isorphaned.toString()+h+"019700101";k=encodeURIComponent(mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?"https://"+
k.langval+"search.yahoo.com/search&type="+h:mcafee_wa_bkglobals.searchURL);h=mcafee_wa_settings.extnversion;if(mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Search){var l=h.indexOf(".");-1!=l&&(h="4"+h.substr(l))}c=(1==c?mcafee_wa_bkconstants.phishingPageUrl:mcafee_wa_bkconstants.blockPageUrl)+"?domain="+b+"&client_ver="+h+"&locale="+f+"&originalURL="+g.getTime();null!=k&&(c+="&searchurl="+k);mcafee_wa_bkglobals.blockPageMap.set(g.getTime().toString(),b);d&&(c+="&subframe=1");e(c);return!0}}}();
function mcafee_wa_onmessagelistener(){}
mcafee_wa_onmessagelistener.prototype.init=function(){try{chrome.runtime.onMessage.addListener(function(a,b,d){var c=!1;try{switch(a.command){case mcafee_wa_commands.ispageblocked:mcafee_wa_extensionstatuschecker.isBlockPageDisabled()||(c=mcafee_wa_bkglobals.messageDispatcher.isPageBlocked(a.Url,function(a,b){d({blocked:a,rediruri:b})}));break;case mcafee_wa_commands.dssrequest:c=mcafee_wa_bkglobals.messageDispatcher.makeDSSRequest(a.Url,a.searchEngineType,a.isSecureSearch,a.requestData,d);break;
case mcafee_wa_commands.reportstat:c=mcafee_wa_bkglobals.messageDispatcher.reportStat(a);break;case mcafee_wa_commands.executecommand:c=mcafee_wa_bkglobals.messageDispatcher.executeCommand(a.commandId,a.params);break;case mcafee_wa_commands.onnavigate:c=mcafee_wa_dispatchwrap.onBeforeNavigate(a.Url,b.tab.id,a.FrameId);c=mcafee_wa_dispatchwrap.onNavigate(a.Url,b.tab.id,a.FrameId);break;case mcafee_wa_commands.getsupportedfeatures:var e=mcafee_wa_supportedfeatures.none;mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]||
(mcafee_wa_extensionstatuschecker.isAnnotationDisabled()||(e=mcafee_wa_supportedfeatures.annotations),mcafee_wa_extensionstatuschecker.isBlockPageDisabled()||(e=e|mcafee_wa_supportedfeatures.blockpages|mcafee_wa_supportedfeatures.iframeblocking));d({features:e,otherextensionenabled:mcafee_wa_bkglobals.otherExtensionEnabled});break;case mcafee_wa_commands.isframeblocked:mcafee_wa_bkglobals.messageDispatcher.isFrameBlocked(a.Url,d);c=!0;break;case mcafee_wa_commands.logmsg:mcafee_wa_bkglobals.messageDispatcher.logMsg(a.logflags,
a.message)}}catch(f){mcafee_wa_bkglobals.logger.error(f)}return c})}catch(a){mcafee_wa_bkglobals.logger.error(a)}};function mcafee_wa_tablistener(){}
mcafee_wa_tablistener.prototype.init=function(){chrome.tabs.onActivated.addListener(function(a){mcafee_wa_bkglobals.activetabId=a.tabId;mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]&&mcafee_wa_browseraction.disable(a.tabId)});chrome.tabs.onCreated.addListener(function(a){mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]?mcafee_wa_browseraction.disable(a.tabId):mcafee_wa_bkglobals.messageDispatcher.executeCommand(3,"")});chrome.tabs.onUpdated.addListener(function(a,b,d){if("complete"==
b.status&&"undefined"!=typeof d.url){b=mcafee_wa_bkglobals.lastUrl;if(null==b||b!=d.url)mcafee_wa_bkglobals.lastUrl=d.url,b="BrowserNavigate_"+mcafee_wa_browsertypefinder.browserTypeToString(mcafee_wa_bkglobals.browserType),mcafee_wa_bkglobals.messageDispatcher.reportStat({Name:b,Value:d.url});mcafee_wa_bkcommon.isSiteAdvisorURL(d.url)?(d=mcafee_wa_msgdispatchhelper.toQualifiedImagePath("small_button_hs.gif"),mcafee_wa_browseraction.setIcon(d,a)):mcafee_wa_bkcommon.isProperWebURL(d.url)||(d=mcafee_wa_msgdispatchhelper.toQualifiedImagePath("small_button_disabled.gif"),
mcafee_wa_browseraction.setIcon(d,a))}})};function mcafee_wa_legacynativemsgdispatcher(){this._port=0;this._callbackId=100;this._messageMap={0:{}};this._contextMap={0:[null,-1]};this._icons=[];this._blockedFrames=new Map}mcafee_wa_legacynativemsgdispatcher.prototype.isPageBlocked=function(a,b){b(!1,null)};mcafee_wa_legacynativemsgdispatcher.prototype.nativeMsg=function(a){var b=!1;try{var d=[1,0].concat(a),b=this.postMessage(d)}catch(c){return mcafee_wa_bkglobals.logger.error(c),!1}return b};
mcafee_wa_legacynativemsgdispatcher.prototype.logMsg=function(a,b){try{this._port.postMessage([1,0,mcafee_wa_nativecommands.logmsg,a,b])}catch(d){}};mcafee_wa_legacynativemsgdispatcher.prototype.postMessage=function(a){try{this._port.postMessage(a)}catch(b){return this._port.disconnect(),this._port=null,mcafee_wa_bkglobals.logger.error(b),!1}return!0};mcafee_wa_legacynativemsgdispatcher.prototype.addNewContext=function(a,b,d,c){this._contextMap[a]={req:b,url:d,topmost:c,refcount:1};return a};
mcafee_wa_legacynativemsgdispatcher.prototype.urlFromContext=function(a){a=this._contextMap[a];if(null!=a&&"undefined"!=typeof a)return a.url};mcafee_wa_legacynativemsgdispatcher.prototype.toTabId=function(a){a=parseInt(a);return isNaN(a)?-1:a<<16>>16};mcafee_wa_legacynativemsgdispatcher.prototype.toFrameId=function(a){var b=parseInt(a);return isNaN(b)?-1:a>>16};
mcafee_wa_legacynativemsgdispatcher.prototype.navigateTab=function(a,b){var d=this.toFrameId(a),c=this.toTabId(a);mcafee_wa_bkglobals.logger.log("Navigate event received from native app for (tabid, frameId, uri) ,"+c+","+d+","+b);if(0==d)mcafee_wa_bkcommon.isSiteAdvisorURL(b)?(d={},d.url=b,chrome.tabs.update(c,d)):chrome.tabs.get(c,function(a){mcafee_wa_bkcommon.isSiteAdvisorURL(a.url)?(a={},a.url=b,chrome.tabs.update(c,a)):chrome.tabs.reload(c,{bypassCache:!0})});else{var e={};e.command=mcafee_wa_commands.onredirectiframe;
e.uri=b;var f=mcafee_wa_uriparser.getParam(b,"domain"),f=unescape(f);this._blockedFrames[f]=b;mcafee_wa_bkglobals.logger.log("Send Message to frame: "+d+" uri: "+b);chrome.tabs.sendMessage(c,e,function(a){"undefined"==typeof a&&"undefined "!=typeof chrome.runtime.lastError&&mcafee_wa_bkglobals.logger.error(chrome.runtime.lastError)})}};
mcafee_wa_legacynativemsgdispatcher.prototype.isFrameBlocked=function(a,b){var d=this._blockedFrames[a];mcafee_wa_bkglobals.logger.log("Checking whether iFrame is blocked for: "+a+". Status is : "+d);b({blocked:"undefined"!=typeof d,uri:d})};mcafee_wa_legacynativemsgdispatcher.prototype.toPageImage=function(a){return a>=this._icons.length?null:mcafee_wa_msgdispatchhelper.toQualifiedImagePath(this._icons[a])};
mcafee_wa_legacynativemsgdispatcher.prototype.setBrowserActionIcon=function(a,b){var d=this.toPageImage(a);null!=d&&mcafee_wa_browseraction.setIcon(d,b)};mcafee_wa_legacynativemsgdispatcher.prototype.changeBrowserAction=function(a,b){if(0==this.toFrameId(a)){var d=this.toTabId(a);this.setBrowserActionIcon(b,d)}};
mcafee_wa_legacynativemsgdispatcher.prototype.processOption=function(a,b){mcafee_wa_bkglobals.options[a]=b;chrome.tabs.query({},function(d){for(var c={command:mcafee_wa_commands.onoptionreceived,optionName:a,optionValue:b},e=0;e<d.length;e++)chrome.tabs.sendMessage(d[e].id,c,null)})};
mcafee_wa_legacynativemsgdispatcher.prototype.getXYViewport=function(){var a={};a.command=mcafee_wa_commands.getxyviewport;var b=this;chrome.tabs.sendMessage(mcafee_wa_bkglobals.activetabId,a,function(a){mcafee_wa_bkglobals.logger.log("X,Y = "+a.X+","+a.Y);b.setSystemOptionString(mcafee_wa_bkconstants.viewport,a.X+","+a.Y)})};
mcafee_wa_legacynativemsgdispatcher.prototype.processInwardMssage=function(a){if(3>a.length)return[];mcafee_wa_bkglobals.logger.log("Processing inward message: "+a[2]+" "+a[3]+" "+a[4]+" "+a[5]);switch(a[2]){case mcafee_wa_jscommands.addbitmap:return this._icons.push(a[3]),this._icons.length-1;case mcafee_wa_jscommands.changebitmap:this.changeBrowserAction(a[5],a[3]);break;case mcafee_wa_jscommands.navigate:this.navigateTab(a[5],a[3]);break;case mcafee_wa_jscommands.urlfromcontext:return this.urlFromContext(a[3]);
case mcafee_wa_jscommands.getxyviewport:return this.getXYViewport();case mcafee_wa_jscommands.refreshsettings:this.syncOptionsToSearchExt()}};
mcafee_wa_legacynativemsgdispatcher.prototype.syncOptionsToSearchExt=function(){var a=this;a.getSystemOptionBool(mcafee_wa_bkconstants.annonlyonssearch,!0,function(b){a.getSystemOptionBool(mcafee_wa_bkconstants.showicons,!0,function(a){mcafee_wa_bkglobals.annotationOption=a?b?mcafee_wa_annotationoptions.OnlySecureSearch:mcafee_wa_annotationoptions.All:mcafee_wa_annotationoptions.none;a=mcafee_wa_supportedextensions.getBuddyExtensions();for(var c=0;c<a.length;++c)chrome.runtime.sendMessage(a[c],{id:mcafee_wa_extensionmsgs.setoptionstring,
option:mcafee_wa_bkglobals.annotationOption})})})};mcafee_wa_legacynativemsgdispatcher.prototype.listen=function(a){var b=this;this._port.onMessage.addListener(function(a){if(!(2>a.length)){var c=parseInt(a[0],10);if(0!=c){var e=b._messageMap[c];null!=e&&"undefined"!=typeof e&&(e.waPromise.resolve({response:a,callback:e.callback,promise:e.waPromise}),delete b._messageMap[c])}else c=b.processInwardMssage(a),b.postMessage([0,a[1],c])}});this._port.onDisconnect.addListener(function(){a({init:!1,disabled:!1})})};
mcafee_wa_legacynativemsgdispatcher.prototype.setSystemOptionString=function(a,b){return this.nativeMsg([mcafee_wa_nativecommands.setsystemoptionstring,a,b])};mcafee_wa_legacynativemsgdispatcher.prototype.getSystemOptionString=function(a,b,d){return this.makePromise(mcafee_wa_nativecommands.getsystemoptionstring,"undefined"==typeof d?null:d,[a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.getSystemOptionBool=function(a,b,d){return this.makePromise(mcafee_wa_nativecommands.getsystemoptionbool,"undefined"==typeof d?null:d,[a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.init=function(a){try{this._port=chrome.runtime.connectNative("siteadvisor.mcafee.chrome.extension"),null!=this._port&&(this.listen(a),this.setSystemOptionString(mcafee_wa_bkconstants.browsertype,mcafee_wa_bkglobals.browserType.toString())&&this.setSystemOptionString(mcafee_wa_bkconstants.useragent,navigator.userAgent)&&(this.getSystemOptionBool(mcafee_wa_bkconstants.notchromecompliant,!0,function(a){mcafee_wa_bkglobals.isChromeCompliant=!a}),this.nativeMsg([mcafee_wa_nativecommands.activate])&&
(this.getSystemOptionString(mcafee_wa_bkconstants.disabled,"0",function(b){a({init:!0,disabled:b})}),this.syncOptionsToSearchExt())))}catch(b){return mcafee_wa_bkglobals.logger.error(b),!1}};mcafee_wa_legacynativemsgdispatcher.prototype.uninit=function(){null!=this._port&&(this._port.disconnect(),this._port=null)};
mcafee_wa_legacynativemsgdispatcher.prototype.then=function(a){try{switch(a.promise.command){case mcafee_wa_nativecommands.getsystemoptionbool:var b=null==a.response[1]||a.response[1];a.promise.pThis.processOption(a.promise.commandParams[0],b);null!=a.callback&&a.callback(b);break;case mcafee_wa_nativecommands.getsystemoptionstring:a.promise.pThis.processOption(a.promise.commandParams[0],a.response[1]);null!=a.callback&&a.callback(a.response[1]);break;case mcafee_wa_nativecommands.ondssrequest:var d=
JSON.parse(a.response[1]);a.callback(d)}}catch(c){mcafee_wa_bkglobals.logger.error(c)}};mcafee_wa_legacynativemsgdispatcher.prototype.makePromise=function(a,b,d){var c=this,e=++this._callbackId,f=new mcafee_wa_promise,g=f.createPromise(function(b,f){var g=[1,e,a].concat(d);c.postMessage(g)},this.then,null,a,d,c);this._messageMap[e]={waPromise:f,callback:b};g.then(this.then);return!0};
mcafee_wa_legacynativemsgdispatcher.prototype.makeDSSRequest=function(a,b,d,c,e){a="dssrequest:multiquery/MultiQuery?tojson=1&href="+a+"&sourceType="+b;c=c.join("\t");return this.makePromise(mcafee_wa_nativecommands.ondssrequest,e,[a,c])};mcafee_wa_legacynativemsgdispatcher.prototype.onDownloadFinished=function(a){this.nativeMsg([mcafee_wa_nativecommands.ondownloadfinished,a.url,a.filename,null==a.referrer?"":a.referrer]);return!1};
mcafee_wa_legacynativemsgdispatcher.prototype.reportStat=function(a){mcafee_wa_bkglobals.logger.log("Stat: "+a.Name+" Value: "+a.Value);this.nativeMsg([mcafee_wa_nativecommands.reportstat,a.Name,"string"==typeof a.Value?a.Value:a.Value.toString()]);return!1};mcafee_wa_legacynativemsgdispatcher.prototype.onSettings=function(a){var b=this.generateContextId(mcafee_wa_bkglobals.activetabId,0);this.addNewContext(b,b,a,!0);this.nativeMsg([mcafee_wa_nativecommands.onMenuItemClick,114,b.toString()]);return!1};
mcafee_wa_legacynativemsgdispatcher.prototype.onDocComplete=function(a){this.nativeMsg([mcafee_wa_nativecommands.ondoccomplete,a,"",0,!0]);return!1};mcafee_wa_legacynativemsgdispatcher.prototype.generateContextId=function(a,b){return-1==b?a:a|b<<16};
mcafee_wa_legacynativemsgdispatcher.prototype.onBeforeNavigate=function(a,b,d){0>=d&&(delete this._blockedFrames,this._blockedFrames=new Map);var c=this.generateContextId(b,d);this.addNewContext(c,c,a,!0);mcafee_wa_bkglobals.logger.log("onBeforeNavigate event called for ( uri, tabId, frameid, contextid) ("+a+","+b+","+d+","+c+")");this.nativeMsg([mcafee_wa_nativecommands.onbeforenavigate,a,c.toString(),c.toString(),0==d]);return!1};
mcafee_wa_legacynativemsgdispatcher.prototype.onNavigate=function(a,b,d){var c=this.generateContextId(b,d);this.addNewContext(c,c,a,!0);mcafee_wa_bkglobals.logger.log("onNavigate event called for ( uri, tabId, frameid, contextid) ("+a+","+b+","+d+","+c+")");this.nativeMsg([mcafee_wa_nativecommands.onnavigate,a,c.toString(),c.toString(),0==d]);return!1};mcafee_wa_legacynativemsgdispatcher.prototype.executeCommand=function(a,b){this.nativeMsg([mcafee_wa_nativecommands.executecommand,a,b])};
mcafee_wa_legacynativemsgdispatcher.prototype.onCSync=function(a,b){this.nativeMsg([mcafee_wa_nativecommands.onCSync,navigator.userAgent,a,b])};
var mcafee_wa_listenermanager=function(){var a=[];return{getListeners:function(){0==a.length&&(a.push(new mcafee_wa_onmessagelistener),a.push(new mcafee_wa_tablistener),a.push(new mcafee_wa_webrequestlistener),mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Firefox?a.push(new mcafee_wa_onchangeddownloadslistener):mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Chrome&&mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main&&a.push(new mcafee_wa_onchangeddownloadslistener),
mcafee_wa_bkglobals.browserType==mcafee_wa_browsertypes.Chrome&&(a.push(new mcafee_wa_extensionmsglistener),a.push(new mcafee_wa_pingsender),mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Search&&a.push(new mcafee_wa_onbeforesendheaderlistener)));return a},getListenersWhenDisabled:function(){0==a.length&&(a.push(new mcafee_wa_tablistener),a.push(new mcafee_wa_onmessagelistener));return a}}}();function mcafee_wa_background(){}
mcafee_wa_background.prototype.processActiveTab=function(){chrome.tabs.query({active:!0},function(a){0!=a.length&&(mcafee_wa_bkglobals.activetabId=a[0].id,a[0].url.startsWith("http://")||a[0].url.startsWith("https://"))&&(mcafee_wa_dispatchwrap.onBeforeNavigate(a[0].url,a[0].id,0),mcafee_wa_dispatchwrap.onNavigate(a[0].url,a[0].id,0))})};
mcafee_wa_background.prototype.handleDisabled=function(){mcafee_wa_bkglobals.messageDispatcher.uninit();for(var a=mcafee_wa_listenermanager.getListenersWhenDisabled(),b=0;b<a.length;++b)a[b].init();chrome.tabs.query({active:!0},function(a){0!=a.length&&mcafee_wa_browseraction.disable(a[0].tabId)})};mcafee_wa_background.prototype.handleEnabled=function(){for(var a=mcafee_wa_listenermanager.getListeners(),b=0;b<a.length;++b)a[b].init();this.processActiveTab()};
mcafee_wa_background.prototype.processInit=function(a){a=parseInt(a);a=mcafee_wa_bkcommon.isDisabled(a,mcafee_wa_bkglobals.browserType);(mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]=a)?this.handleDisabled():this.handleEnabled()};mcafee_wa_background.prototype.createDispatcher=function(){return mcafee_wa_settings.extensiontype==mcafee_wa_extensiontypes.Main?new mcafee_wa_legacynativemsgdispatcher:new mcafee_wa_pnaclmsgdispatcher};
mcafee_wa_background.prototype.main=function(){mcafee_wa_settings.loggertype==mcafee_wa_loggertype.nativeLogger&&(mcafee_wa_bkglobals.logger=new mcafee_wa_bknativelogger);mcafee_wa_bkglobals.logger.SetLogTypes(mcafee_wa_settings.logtype);mcafee_wa_bkglobals.options[mcafee_wa_bkconstants.disabled]=!1;mcafee_wa_bkglobals.browserType=mcafee_wa_browsertypefinder.getBrowserType(mcafee_wa_settings.browsertype);var a=this;mcafee_wa_bkglobals.messageDispatcher=this.createDispatcher();mcafee_wa_bkglobals.messageDispatcher.init(function(b){1==
b.init&&a.processInit(b.disabled)})};var bkobj=new mcafee_wa_background;bkobj.main();
